// Placeholder data for Phase 1. Shape mirrors what real API responses will
// return after Phase 2 wires up the employees, departments, and projects
// endpoints. See types.ts for the canonical shapes.
//
// TODO[Phase 2]: Replace with API-driven data. See README in this folder.

import type {
  OrgDepartment,
  OrgEmployee,
  OrgProject,
  OrgRecentUpdate,
} from "./types";

export const MOCK_DEPARTMENTS: OrgDepartment[] = [
  {
    id: "eng",
    name: "Engineering",
    color: "#4f46e5",
    soft: "#eef2ff",
    count: 12,
  },
  { id: "design", name: "Design", color: "#ea580c", soft: "#fff7ed", count: 3 },
  {
    id: "product",
    name: "Product",
    color: "#7c3aed",
    soft: "#f5f3ff",
    count: 2,
  },
  { id: "people", name: "People", color: "#16a34a", soft: "#f0fdf4", count: 4 },
  { id: "sales", name: "Sales", color: "#e11d48", soft: "#fff1f2", count: 2 },
  { id: "mkt", name: "Marketing", color: "#d97706", soft: "#fffbeb", count: 1 },
  {
    id: "cs",
    name: "Customer Success",
    color: "#0891b2",
    soft: "#ecfeff",
    count: 1,
  },
  {
    id: "ops",
    name: "Operations",
    color: "#475569",
    soft: "#f1f5f9",
    count: 3,
  },
  { id: "fin", name: "Finance", color: "#059669", soft: "#ecfdf5", count: 2 },
  {
    id: "exec",
    name: "Executive",
    color: "#171717",
    soft: "#f3f4f6",
    count: 5,
  },
];

export const MOCK_EMPLOYEES: OrgEmployee[] = [
  {
    id: 1,
    name: "Hana Mehić",
    role: "Chief Executive Officer",
    deptId: "exec",
    managerId: null,
    isManager: true,
    status: "active",
    email: "hana@bloomteq.com",
    phone: "+387 33 555 100",
    location: "Sarajevo",
    startDate: "2018-01-15",
    skills: ["Leadership", "Strategy", "Fundraising"],
  },
  {
    id: 2,
    name: "Senad Halilović",
    role: "Chief Technology Officer",
    deptId: "eng",
    managerId: 1,
    isManager: true,
    status: "active",
    email: "senad@bloomteq.com",
    phone: "+387 33 555 101",
    location: "Sarajevo",
    startDate: "2018-04-02",
    skills: ["Architecture", "Engineering Leadership", "Cloud"],
  },
  {
    id: 3,
    name: "Almir Begović",
    role: "Chief Financial Officer",
    deptId: "fin",
    managerId: 1,
    isManager: true,
    status: "active",
    email: "almir@bloomteq.com",
    phone: "+387 33 555 102",
    location: "Sarajevo",
    startDate: "2019-02-01",
    skills: ["FP&A", "Tax", "Reporting"],
  },
  {
    id: 4,
    name: "Lana Bukvić",
    role: "Chief Product Officer",
    deptId: "product",
    managerId: 1,
    isManager: true,
    status: "active",
    email: "lana@bloomteq.com",
    phone: "+387 33 555 103",
    location: "Sarajevo",
    startDate: "2020-03-10",
    skills: ["Product Strategy", "Discovery", "Roadmapping"],
  },
  {
    id: 5,
    name: "Mirsad Karić",
    role: "Chief Revenue Officer",
    deptId: "sales",
    managerId: 1,
    isManager: true,
    status: "active",
    email: "mirsad@bloomteq.com",
    phone: "+387 33 555 104",
    location: "Banja Luka",
    startDate: "2020-09-21",
    skills: ["Sales", "GTM", "Partnerships"],
  },
  {
    id: 12,
    name: "Aida Salihović",
    role: "Head of People",
    deptId: "people",
    managerId: 1,
    isManager: true,
    status: "active",
    email: "aida@bloomteq.com",
    phone: "+387 61 200 012",
    location: "Sarajevo",
    startDate: "2019-06-01",
    skills: ["People Ops", "Employee Relations", "Comp & Bens"],
  },
  {
    id: 18,
    name: "Asmin Bašić",
    role: "Engineering Manager",
    deptId: "eng",
    managerId: 2,
    isManager: true,
    status: "active",
    email: "asmin@bloomteq.com",
    phone: "+387 61 200 018",
    location: "Sarajevo",
    startDate: "2020-09-15",
    skills: ["Go", "Kubernetes", "People Mgmt"],
  },
  {
    id: 56,
    name: "Dženana Hodžić",
    role: "Head of Design",
    deptId: "design",
    managerId: 4,
    isManager: true,
    status: "active",
    email: "dzenana@bloomteq.com",
    phone: "+387 61 200 056",
    location: "Sarajevo",
    startDate: "2023-04-10",
    skills: ["Product Design", "Design Systems", "Research"],
  },
  {
    id: 104,
    name: "Sanja Đurić",
    role: "Senior Product Manager",
    deptId: "product",
    managerId: 4,
    isManager: true,
    status: "active",
    email: "sanja@bloomteq.com",
    phone: "+387 61 200 104",
    location: "Sarajevo",
    startDate: "2021-04-19",
    skills: ["Discovery", "PRDs", "Stakeholder Mgmt"],
  },
  {
    id: 148,
    name: "Selma Karić",
    role: "Marketing Manager",
    deptId: "mkt",
    managerId: 5,
    isManager: true,
    status: "active",
    email: "selma.k@bloomteq.com",
    phone: "+387 61 200 148",
    location: "Sarajevo",
    startDate: "2022-05-30",
    skills: ["Brand", "Performance Mktg", "SEO"],
  },
  {
    id: 159,
    name: "Adisa Smajić",
    role: "Customer Success Lead",
    deptId: "cs",
    managerId: 5,
    isManager: true,
    status: "active",
    email: "adisa@bloomteq.com",
    phone: "+387 61 200 159",
    location: "Sarajevo",
    startDate: "2023-06-12",
    skills: ["Customer Onboarding", "Renewals", "QBRs"],
  },
  {
    id: 174,
    name: "Ena Krupalija",
    role: "Finance Manager",
    deptId: "fin",
    managerId: 3,
    isManager: true,
    status: "active",
    email: "ena@bloomteq.com",
    phone: "+387 61 200 174",
    location: "Sarajevo",
    startDate: "2021-01-25",
    skills: ["Reporting", "Audit", "Tax"],
  },
  {
    id: 185,
    name: "Tarik Pehlić",
    role: "Head of Operations",
    deptId: "ops",
    managerId: 1,
    isManager: true,
    status: "active",
    email: "tarik.p@bloomteq.com",
    phone: "+387 61 200 185",
    location: "Sarajevo",
    startDate: "2020-11-04",
    skills: ["IT Ops", "Vendor Mgmt", "Procurement"],
  },
  {
    id: 31,
    name: "Ahmed Burić",
    role: "DevOps Lead",
    deptId: "eng",
    managerId: 2,
    isManager: true,
    status: "active",
    email: "ahmed@bloomteq.com",
    phone: "+387 61 200 031",
    location: "Mostar",
    startDate: "2022-11-07",
    skills: ["Terraform", "AWS", "CI/CD"],
  },
  {
    id: 67,
    name: "Mirza Kovač",
    role: "Mobile Lead",
    deptId: "eng",
    managerId: 2,
    isManager: true,
    status: "onLeave",
    email: "mirza@bloomteq.com",
    phone: "+387 61 200 067",
    location: "Banja Luka",
    startDate: "2021-08-23",
    skills: ["Swift", "Architecture", "Mentoring"],
  },
  {
    id: 71,
    name: "Lejla Ibrahimović",
    role: "QA Lead",
    deptId: "eng",
    managerId: 2,
    isManager: true,
    status: "active",
    email: "lejla@bloomteq.com",
    phone: "+387 61 200 071",
    location: "Sarajevo",
    startDate: "2024-01-08",
    skills: ["Playwright", "Test Strategy", "Automation"],
  },
  {
    id: 141,
    name: "Damir Hamzić",
    role: "Web Tech Lead",
    deptId: "eng",
    managerId: 2,
    isManager: true,
    status: "active",
    email: "damir@bloomteq.com",
    phone: "+387 61 200 141",
    location: "Sarajevo",
    startDate: "2020-12-10",
    skills: ["React", "TypeScript", "Next.js"],
  },
  {
    id: 42,
    name: "Tarik Mujanović",
    role: "Senior Backend Engineer",
    deptId: "eng",
    managerId: 18,
    isManager: false,
    status: "active",
    email: "tarik@bloomteq.com",
    phone: "+387 61 234 567",
    location: "Sarajevo",
    startDate: "2022-03-01",
    skills: ["Go", "PostgreSQL", "Kubernetes", "gRPC", "Terraform"],
  },
  {
    id: 92,
    name: "Vedad Memić",
    role: "Backend Engineer",
    deptId: "eng",
    managerId: 18,
    isManager: false,
    status: "active",
    email: "vedad@bloomteq.com",
    phone: "+387 61 200 092",
    location: "Sarajevo",
    startDate: "2024-09-02",
    skills: ["Go", "Postgres"],
  },
  {
    id: 152,
    name: "Muhamed Begić",
    role: "Backend Engineer",
    deptId: "eng",
    managerId: 18,
    isManager: false,
    status: "onLeave",
    email: "muhamed@bloomteq.com",
    phone: "+387 61 200 152",
    location: "Tuzla",
    startDate: "2021-10-04",
    skills: ["Python", "Django"],
  },
  {
    id: 23,
    name: "Hanan Bajramović",
    role: "Frontend Engineer",
    deptId: "eng",
    managerId: 141,
    isManager: false,
    status: "active",
    email: "hanan@bloomteq.com",
    phone: "+387 61 200 023",
    location: "Sarajevo",
    startDate: "2023-02-13",
    skills: ["React", "CSS", "Storybook"],
  },
  {
    id: 125,
    name: "Tarik Selimović",
    role: "Junior Frontend Engineer",
    deptId: "eng",
    managerId: 141,
    isManager: false,
    status: "remote",
    email: "tarik.s@bloomteq.com",
    phone: "+387 61 200 125",
    location: "Sarajevo (remote)",
    startDate: "2026-03-15",
    skills: ["React", "Tailwind"],
  },
  {
    id: 181,
    name: "Jasmin Hodžić",
    role: "DevOps Engineer",
    deptId: "eng",
    managerId: 31,
    isManager: false,
    status: "active",
    email: "jasmin@bloomteq.com",
    phone: "+387 61 200 181",
    location: "Sarajevo",
    startDate: "2019-11-08",
    skills: ["AWS", "Ansible", "Linux"],
  },
  {
    id: 112,
    name: "Kemal Hadžić",
    role: "Android Engineer",
    deptId: "eng",
    managerId: 67,
    isManager: false,
    status: "remote",
    email: "kemal@bloomteq.com",
    phone: "+387 61 200 112",
    location: "Mostar (remote)",
    startDate: "2022-07-25",
    skills: ["Kotlin", "Jetpack Compose"],
  },
  {
    id: 118,
    name: "Maja Kapetanović",
    role: "Brand Designer",
    deptId: "design",
    managerId: 56,
    isManager: false,
    status: "active",
    email: "maja@bloomteq.com",
    phone: "+387 61 200 118",
    location: "Sarajevo",
    startDate: "2024-03-11",
    skills: ["Brand", "Illustration"],
  },
  {
    id: 201,
    name: "Nadina Šabanović",
    role: "Product Designer",
    deptId: "design",
    managerId: 56,
    isManager: false,
    status: "active",
    email: "nadina@bloomteq.com",
    phone: "+387 61 200 201",
    location: "Sarajevo",
    startDate: "2024-11-04",
    skills: ["Figma", "Prototyping", "UX"],
  },
  {
    id: 84,
    name: "Amila Halilović",
    role: "People Partner",
    deptId: "people",
    managerId: 12,
    isManager: false,
    status: "active",
    email: "amila@bloomteq.com",
    phone: "+387 61 200 084",
    location: "Sarajevo",
    startDate: "2024-06-17",
    skills: ["Engagement", "Performance Reviews"],
  },
  {
    id: 133,
    name: "Ivana Petrović",
    role: "Recruiter",
    deptId: "people",
    managerId: 12,
    isManager: false,
    status: "active",
    email: "ivana@bloomteq.com",
    phone: "+387 61 200 133",
    location: "Banja Luka",
    startDate: "2023-11-20",
    skills: ["Sourcing", "Tech Recruiting"],
  },
  {
    id: 79,
    name: "Edin Šabić",
    role: "Account Executive",
    deptId: "sales",
    managerId: 5,
    isManager: false,
    status: "active",
    email: "edin@bloomteq.com",
    phone: "+387 61 200 079",
    location: "Tuzla",
    startDate: "2023-09-04",
    skills: ["Outbound", "Negotiation"],
  },
  {
    id: 98,
    name: "Nedim Pašić",
    role: "Data Analyst",
    deptId: "ops",
    managerId: 185,
    isManager: false,
    status: "active",
    email: "nedim@bloomteq.com",
    phone: "+387 61 200 098",
    location: "Sarajevo",
    startDate: "2026-02-03",
    skills: ["SQL", "dbt", "Looker"],
  },
  {
    id: 167,
    name: "Boris Tomić",
    role: "IT Support Specialist",
    deptId: "ops",
    managerId: 185,
    isManager: false,
    status: "active",
    email: "boris@bloomteq.com",
    phone: "+387 61 200 167",
    location: "Sarajevo",
    startDate: "2024-08-19",
    skills: ["Helpdesk", "MDM"],
  },
];

export const MOCK_PROJECTS: OrgProject[] = [
  {
    id: "atlas",
    name: "Project Atlas",
    status: "Active",
    memberIds: [42, 18, 92, 2],
  },
  {
    id: "mercury",
    name: "Mercury Internal Tools",
    status: "Active",
    memberIds: [18, 23, 141],
  },
  {
    id: "horizon",
    name: "Horizon Mobile App",
    status: "Active",
    memberIds: [67, 112, 2],
  },
  {
    id: "orion",
    name: "Orion Data Warehouse",
    status: "On hold",
    memberIds: [31, 98, 185],
  },
  {
    id: "phoenix",
    name: "Phoenix Billing Engine",
    status: "Active",
    memberIds: [152, 42, 174, 3],
  },
  {
    id: "pioneer",
    name: "Pioneer QA Automation",
    status: "Active",
    memberIds: [71, 31],
  },
];

export const MOCK_RECENT_UPDATES: OrgRecentUpdate[] = [
  {
    id: "u1",
    kind: "reassign",
    text: "Vedad Memić now reports to Asmin Bašić",
    at: "2 hours ago",
  },
  {
    id: "u2",
    kind: "hire",
    text: "Nadina Šabanović joined Design",
    at: "yesterday",
  },
  {
    id: "u3",
    kind: "promote",
    text: "Tarik Mujanović promoted to L4 Senior",
    at: "3 days ago",
  },
  {
    id: "u4",
    kind: "leave",
    text: "Mirza Kovač started parental leave",
    at: "1 week ago",
  },
];
